package io.genfin.payment.failure;

public enum FailureCategory {
  INSUFFICIENT_FUNDS,
  CARD_DECLINED,
  EXPIRED_PAYMENT_METHOD,
  FRAUD_SUSPECTED,
  AUTHENTICATION_REQUIRED,
  NETWORK_ERROR,
  PROVIDER_ERROR,
  INVALID_PAYMENT_METHOD,
  TIMEOUT,
  UNKNOWN
}
