-- CreateTable
CREATE TABLE "search_index" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "tenant_id" UUID NOT NULL,
    "entity_type" VARCHAR(64) NOT NULL,
    "entity_id" UUID NOT NULL,
    "title" VARCHAR(512) NOT NULL,
    "snippet" TEXT,
    "content" TEXT,
    "owner_id" UUID,
    "metadata" JSONB NOT NULL DEFAULT '{}',
    "tsv" tsvector,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "search_index_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "search_index_tenant_id_entity_type_entity_id_key" ON "search_index"("tenant_id", "entity_type", "entity_id");

-- CreateIndex
CREATE INDEX "search_index_tenant_id_idx" ON "search_index"("tenant_id");

-- CreateIndex
CREATE INDEX "search_index_tenant_id_entity_type_idx" ON "search_index"("tenant_id", "entity_type");

-- CreateIndex
CREATE INDEX "search_index_owner_id_idx" ON "search_index"("owner_id");

-- CreateIndex (GIN, for full-text search via `tsv @@ plainto_tsquery(...)`)
CREATE INDEX "search_index_tsv_idx" ON "search_index" USING GIN ("tsv");

-- Keeps `tsv` in sync with title/snippet/content on every insert/update,
-- regardless of whether the write came through raw SQL or Prisma Client.
-- Prisma's Unsupported("tsvector") type means this can't be expressed in
-- schema.prisma or generated by `prisma migrate dev` — it's hand-maintained
-- here, same as every other statement in this file.
CREATE FUNCTION search_index_tsv_trigger() RETURNS trigger AS $$
BEGIN
  NEW.tsv := to_tsvector('english',
    coalesce(NEW.title, '') || ' ' || coalesce(NEW.snippet, '') || ' ' || coalesce(NEW.content, '')
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER search_index_tsv_update
  BEFORE INSERT OR UPDATE ON "search_index"
  FOR EACH ROW EXECUTE FUNCTION search_index_tsv_trigger();
