package com.company.bsmsvc.domain.enums;

public enum InvoiceSource {
    /** Created manually via API by an operator or admin. */
    MANUAL,
    /** Auto-generated by the renewal scheduler at the start of a new billing period. */
    SUBSCRIPTION_RENEWAL,
    /** Generated when a subscription is upgraded to a higher plan. */
    UPGRADE,
    /** Generated as a prorated adjustment when a subscription is downgraded. */
    DOWNGRADE,
    /** One-off billing adjustment invoice. */
    ADJUSTMENT,
    /** Generated when a PPM add-on is purchased and attached to a subscription. */
    ADDON_PURCHASE
}
