package com.company.bsmsvc.domain.enums;

public enum SubscriptionEventType {
    SUBSCRIPTION_CREATED,
    SUBSCRIPTION_PAUSED,
    SUBSCRIPTION_RESUMED,
    SUBSCRIPTION_CANCELLED,
    SUBSCRIPTION_SCHEDULED_FOR_CANCELLATION,
    SUBSCRIPTION_DOWNGRADE_SCHEDULED,
    SUBSCRIPTION_DOWNGRADE_CANCELLED,
    SUBSCRIPTION_UPGRADED,
    SUBSCRIPTION_DOWNGRADED,
    PRORATION_PREVIEW_GENERATED,
    DOWNGRADE_PREFLIGHT_EXECUTED,
    MIGRATION_PLAN_CREATED,
    SUBSCRIPTION_ACTIVATED,
    SUBSCRIPTION_PPM_PLAN_CHANGED,
    SUBSCRIPTION_ADDON_PURCHASED,
    SUBSCRIPTION_ADDON_REMOVED
}
