package com.company.ppmdemo;

import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;

import java.util.UUID;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

/**
 * Boots the real {@link PpmDemoApplication} — real ppm-core use-case beans,
 * real in-memory port adapters, real Spring MVC dispatch — and exercises it
 * over HTTP exactly as the Phase 5 manual {@code curl} session did, but
 * automated. This is the regression net for both this module and
 * {@code ppm-spring-boot-starter}/{@code ppm-core}: any change that breaks
 * this test means a real consumer's wiring broke, not just a unit.
 *
 * <p>Deliberately does NOT use {@code @MockBean} for any ppm-core service —
 * the whole point is proving the real component-scan configuration in
 * {@link PpmDemoApplication} (including its two documented scan-scoping
 * workarounds) produces a working application end to end.
 *
 * <p>Tests run in a fixed order ({@code @TestMethodOrder}) because they build
 * on shared state (a plan and module created in one test are referenced in
 * later ones) — the same sequence as the original manual verification.
 */
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.MOCK)
@AutoConfigureMockMvc
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
class PpmDemoApplicationIntegrationTest {

    @Autowired MockMvc mockMvc;

    private static String planId;
    private static String moduleId;

    @Test
    @Order(1)
    void createPlan_returns201WithAutoGeneratedSlug() throws Exception {
        String response = mockMvc.perform(post("/demo/plans")
                .contentType(MediaType.APPLICATION_JSON)
                .content("""
                    {"code":"starter","name":"Starter Plan","trialDays":14}
                    """))
            .andExpect(status().isCreated())
            .andExpect(jsonPath("$.code").value("starter"))
            .andExpect(jsonPath("$.slug").value("PLN-0001"))
            .andExpect(jsonPath("$.active").value(true))
            .andExpect(jsonPath("$.trialDays").value(14))
            .andReturn().getResponse().getContentAsString();

        planId = extractField(response, "id");
    }

    @Test
    @Order(2)
    void listPlans_returnsTheCreatedPlan() throws Exception {
        mockMvc.perform(get("/demo/plans"))
            .andExpect(status().isOk())
            .andExpect(jsonPath("$.length()").value(1))
            .andExpect(jsonPath("$[0].id").value(planId));
    }

    @Test
    @Order(3)
    void createModule_returns201() throws Exception {
        String response = mockMvc.perform(post("/demo/modules")
                .contentType(MediaType.APPLICATION_JSON)
                .content("""
                    {"code":"invoicing","name":"Invoicing","description":"Invoicing module"}
                    """))
            .andExpect(status().isCreated())
            .andExpect(jsonPath("$.code").value("invoicing"))
            .andReturn().getResponse().getContentAsString();

        moduleId = extractField(response, "id");
    }

    @Test
    @Order(4)
    void assignModuleToPlan_composesAcrossThreeAggregates() throws Exception {
        // Proves PlanModuleApplicationService, Plan, and Module all resolve correctly
        // together through the real in-memory adapters — not just individually.
        mockMvc.perform(post("/demo/plans/{planId}/modules/{moduleId}", planId, moduleId))
            .andExpect(status().isOk())
            .andExpect(jsonPath("$.length()").value(1))
            .andExpect(jsonPath("$[0].id").value(moduleId))
            .andExpect(jsonPath("$[0].code").value("invoicing"));
    }

    @Test
    @Order(5)
    void assignModuleToUnknownPlan_returns404ViaGlobalExceptionHandler() throws Exception {
        // PlanModuleApplicationServiceImpl.assignModules verifies the plan exists (BR-1)
        // before touching modules — ResourceNotFoundException(PLAN_NOT_FOUND), mapped to
        // 404 by GlobalExceptionHandler.
        mockMvc.perform(post("/demo/plans/{planId}/modules/{moduleId}",
                UUID.randomUUID(), UUID.randomUUID()))
            .andExpect(status().isNotFound())
            .andExpect(jsonPath("$.code").value("PPM-2001"));
    }

    @Test
    @Order(6)
    void createPromoCode_returns201() throws Exception {
        mockMvc.perform(post("/demo/promo-codes")
                .contentType(MediaType.APPLICATION_JSON)
                .content("""
                    {"code":"SUMMER20","discountType":"percentage","value":20,
                     "validFrom":"2020-01-01","validUntil":"2030-01-01"}
                    """))
            .andExpect(status().isCreated())
            .andExpect(jsonPath("$.code").value("SUMMER20"))
            .andExpect(jsonPath("$.active").value(true));
    }

    @Test
    @Order(7)
    void validatePromoCode_validCase_returnsValidTrue() throws Exception {
        mockMvc.perform(post("/demo/promo-codes/validate")
                .contentType(MediaType.APPLICATION_JSON)
                .content("""
                    {"code":"SUMMER20","planId":"%s"}
                    """.formatted(planId)))
            .andExpect(status().isOk())
            .andExpect(jsonPath("$.valid").value(true))
            .andExpect(jsonPath("$.reason").value("valid"));
    }

    @Test
    @Order(8)
    void validatePromoCode_unknownCode_returnsValidFalse() throws Exception {
        mockMvc.perform(post("/demo/promo-codes/validate")
                .contentType(MediaType.APPLICATION_JSON)
                .content("""
                    {"code":"NOPE","planId":"%s"}
                    """.formatted(planId)))
            .andExpect(status().isOk())
            .andExpect(jsonPath("$.valid").value(false))
            .andExpect(jsonPath("$.reason").value("promo_not_found"));
    }

    @Test
    @Order(9)
    void validatePromoCode_unknownPlan_returns404ViaGlobalExceptionHandler() throws Exception {
        // PromoValidationService.validate throws ResourceNotFoundException for an unknown
        // plan — this is the one path GlobalExceptionHandler's mapping is actually exercised
        // by an end-to-end request in this test class.
        mockMvc.perform(post("/demo/promo-codes/validate")
                .contentType(MediaType.APPLICATION_JSON)
                .content("""
                    {"code":"SUMMER20","planId":"%s"}
                    """.formatted(UUID.randomUUID())))
            .andExpect(status().isNotFound())
            .andExpect(jsonPath("$.code").value("PPM-2001"));
    }

    private static String extractField(String json, String field) {
        Matcher m = Pattern.compile("\"" + field + "\":\"([^\"]+)\"").matcher(json);
        if (!m.find()) {
            throw new AssertionError("Field \"" + field + "\" not found in: " + json);
        }
        return m.group(1);
    }
}
