package com.company.bsmsvc.application.service;

import com.company.bsmsvc.domain.model.MigrationPlan;
import com.company.bsmsvc.domain.model.MigrationPlanFilter;
import com.company.bsmsvc.domain.model.MigrationPlanItem;
import com.company.bsmsvc.domain.model.PageResult;
import java.util.List;
import java.util.UUID;

public interface MigrationPlanService {

    /**
     * Persists a migration plan along with its items.
     *
     * @param plan  header record (id must be pre-generated by caller)
     * @param items list of resource items to associate with the plan
     * @return the saved plan with items attached
     */
    MigrationPlan createMigrationPlan(MigrationPlan plan, List<MigrationPlanItem> items);

    /**
     * Retrieves a migration plan by its ID (items populated).
     */
    MigrationPlan getMigrationPlan(UUID id);

    PageResult<MigrationPlan> listMigrationPlans(
        MigrationPlanFilter filter,
        int page,
        int size,
        String sortBy,
        String sortDir
    );
}
