package io.genfin.demo.invoice;

import io.genfin.api.spi.ExtensionRegistry;
import io.genfin.document.api.compose.ComposedDocument;
import io.genfin.document.api.compose.DocumentComposer;
import io.genfin.document.api.compose.DocumentComposers;
import io.genfin.document.api.identity.DocumentId;
import io.genfin.document.api.identity.RendererId;
import io.genfin.document.api.model.DocumentAttributes;
import io.genfin.document.api.model.DocumentMetadata;
import io.genfin.document.api.model.DocumentModel;
import io.genfin.document.api.model.DocumentSection;
import io.genfin.document.api.model.StandardDocumentType;
import io.genfin.document.api.model.TextBlockElement;
import io.genfin.document.api.result.RenderResult;
import io.genfin.document.port.DocumentRenderer;
import io.genfin.document.port.RendererConfiguration;
import io.genfin.document.port.RendererResolver;
import io.genfin.invoice.port.calculation.InvoiceCalculator;
import io.genfin.payment.gateway.GatewayCapabilities;
import io.genfin.payment.gateway.GatewayHealth;
import io.genfin.payment.gateway.GatewayRequest;
import io.genfin.payment.gateway.GatewayResponse;
import io.genfin.payment.gateway.PaymentProvider;
import io.genfin.payment.gateway.ProviderCapabilities;
import io.genfin.payment.method.StandardPaymentMethodType;
import io.genfin.payment.port.gateway.PaymentGateway;
import java.nio.charset.StandardCharsets;
import java.time.Instant;
import java.util.List;
import java.util.Set;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

/**
 * Demonstrates fin-spring-boot-starter end to end: an injected {@link ExtensionRegistry} resolving
 * fin-invoice's default extension (no manual {@code registerDefaults} call anywhere here), a custom
 * {@link PaymentGateway} bean discovered automatically by {@code PaymentAutoConfiguration}, and a
 * document rendered via the same registry. Console output only — no REST endpoints.
 */
@SpringBootApplication
public class InvoiceDemoApplication {

  public static void main(String[] args) {
    SpringApplication.run(InvoiceDemoApplication.class, args);
  }

  /**
   * Registering a {@link PaymentGateway} bean here is all an application needs to do —
   * {@code PaymentAutoConfiguration} discovers it and adds it to the shared {@code
   * GatewayRegistry} with no other wiring.
   */
  @Bean
  PaymentGateway demoGateway() {
    return new DemoPaymentGateway();
  }

  @Bean
  CommandLineRunner run(ExtensionRegistry registry) {
    return args -> {
      System.out.println("Registered InvoiceCalculator: " + registry.find(InvoiceCalculator.class));

      RendererResolver renderers = registry.find(RendererResolver.class).orElseThrow();
      DocumentRenderer jsonRenderer = renderers.resolve(RendererId.of("json"));

      DocumentComposer composer = DocumentComposers.noOp();
      DocumentModel model =
          DocumentModel.of(
              DocumentMetadata.of(
                  DocumentId.generate(), StandardDocumentType.INVOICE, "en-US", "USD", Instant.now()),
              List.of(
                  DocumentSection.of(
                      "Summary", List.of(TextBlockElement.of("Invoice generated by demo-invoice")))),
              DocumentAttributes.empty());
      ComposedDocument document = composer.compose(model);

      RenderResult result = jsonRenderer.render(document, RendererConfiguration.defaults());
      System.out.println("Rendered document (" + result.mimeType() + "):");
      System.out.println(new String(result.content(), StandardCharsets.UTF_8));
    };
  }

  /** A trivial in-memory gateway — just enough to prove automatic discovery, never a real charge. */
  static final class DemoPaymentGateway implements PaymentGateway {

    @Override
    public GatewayResponse authorize(GatewayRequest request) {
      return GatewayResponse.success("demo-authorization", null);
    }

    @Override
    public GatewayResponse capture(GatewayRequest request) {
      return GatewayResponse.success("demo-capture", null);
    }

    @Override
    public GatewayResponse voidAuthorization(GatewayRequest request) {
      return GatewayResponse.success("demo-void", null);
    }

    @Override
    public GatewayResponse refund(GatewayRequest request) {
      return GatewayResponse.success("demo-refund", null);
    }

    @Override
    public GatewayCapabilities capabilities() {
      return new GatewayCapabilities(
          true, true, true, true, false, Set.of(StandardPaymentMethodType.CARD));
    }

    @Override
    public GatewayHealth health() {
      return GatewayHealth.up(Instant.now());
    }

    @Override
    public PaymentProvider provider() {
      return new PaymentProvider(
          "demo", "Demo Gateway", new ProviderCapabilities(Set.of("USD"), Set.of("US"), false, false));
    }
  }
}
