package com.example.bsmdemo;

import static org.assertj.core.api.Assertions.assertThat;

import com.company.bsmsvc.application.service.DunningService;
import com.company.bsmsvc.application.service.InvoiceRenewalService;
import com.company.bsmsvc.application.service.InvoiceService;
import com.company.bsmsvc.application.service.PaymentMethodService;
import com.company.bsmsvc.application.service.PaymentService;
import com.company.bsmsvc.application.service.SubscriptionService;
import com.company.bsmsvc.application.service.TenantOnboardingService;
import com.company.bsmsvc.domain.enums.InvoiceStatus;
import com.company.bsmsvc.domain.enums.PaymentMethodType;
import com.company.bsmsvc.domain.enums.SubscriptionStatus;
import com.company.bsmsvc.domain.model.InvoiceFilter;
import com.company.bsmsvc.domain.model.OnboardTenantCommand;
import com.company.bsmsvc.domain.model.PlatformInvoice;
import com.company.bsmsvc.domain.model.Subscription;
import com.company.bsmsvc.domain.model.payment.PaymentIntentResult;
import java.util.UUID;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

/**
 * Second-consumer validation: exercises the full Billing workflow using ONLY bsm-core's
 * public application services, wired against bsm-demo's in-memory adapters. Zero bsm-svc,
 * zero CPMS-specific code, zero JPA/HTTP/Rabbit/Stripe.
 *
 * Create Tenant → Resolve Trial/Plan → Create Subscription → Generate Invoice →
 * Simulate Payment → Renew Subscription → Trigger Dunning.
 */
@SpringBootTest
class EndToEndWorkflowTest {

    @Autowired TenantOnboardingService tenantOnboardingService;
    @Autowired SubscriptionService subscriptionService;
    @Autowired InvoiceService invoiceService;
    @Autowired PaymentMethodService paymentMethodService;
    @Autowired PaymentService paymentService;
    @Autowired InvoiceRenewalService invoiceRenewalService;
    @Autowired DunningService dunningService;

    @Test
    void fullBillingLifecycle_executesEndToEndThroughBsmCoreOnly() {
        UUID tenantId = UUID.randomUUID();
        UUID ppmPlanId = UUID.randomUUID();
        UUID ppmPlanVersionId = UUID.randomUUID();

        // 1. Onboard tenant onto a paid plan (admin-provisioned — invoice stays OPEN, not auto-paid)
        tenantOnboardingService.onboard(new OnboardTenantCommand(
            tenantId, "MONTHLY", ppmPlanId, ppmPlanVersionId, "DEMO_REGION", "SUP_SVC_PROVISIONED"));

        Subscription subscription = subscriptionService.getCurrentSubscription(tenantId);
        assertThat(subscription).isNotNull();
        assertThat(subscription.getStatus()).isEqualTo(SubscriptionStatus.ACTIVE);
        assertThat(subscription.getPpmPlanId()).isEqualTo(ppmPlanId);

        // 2. First invoice was generated by onboarding and left OPEN (nothing paid yet)
        PlatformInvoice firstInvoice = invoiceService.searchInvoices(
            new InvoiceFilter(tenantId, null, null, null), 0, 10, "createdAt", "DESC")
            .content().get(0);
        assertThat(firstInvoice.getStatus()).isEqualTo(InvoiceStatus.OPEN);
        assertThat(firstInvoice.getAmountDue()).isGreaterThan(0L);

        // 3. Register a payment method — creates the gateway customer the payment intent needs
        paymentMethodService.createCustomerIfRequired(tenantId, "Demo Tenant", "demo@example.com");
        paymentMethodService.addPaymentMethod(
            tenantId, "tok_demo", PaymentMethodType.CARD, "VISA", "4242", 12, 2030, true);

        // 4. Simulate payment via the payment gateway port
        PaymentIntentResult intent = paymentService.createPaymentIntent(tenantId, firstInvoice.getId());
        assertThat(intent).isNotNull();
        assertThat(intent.status()).isEqualTo("SUCCEEDED");

        // 5. Apply the payment to the invoice
        PlatformInvoice paidInvoice = invoiceService.applyPayment(firstInvoice.getId(), firstInvoice.getAmountDue(), null);
        assertThat(paidInvoice.getStatus()).isEqualTo(InvoiceStatus.PAID);

        // 6. Renew the subscription — a new invoice for the next period
        PlatformInvoice renewalInvoice = invoiceRenewalService.generateRenewalInvoice(subscription);
        assertThat(renewalInvoice).isNotNull();
        assertThat(renewalInvoice.getSubscriptionId()).isEqualTo(subscription.getId());

        // 7. Trigger dunning on the (unpaid) renewal invoice
        dunningService.startDunning(subscription.getId(), renewalInvoice.getId());
        assertThat(subscriptionService.getCurrentSubscription(tenantId).isInDunning()).isTrue();

        // 8. Recover — payment received while in dunning
        dunningService.recoveryPaymentReceived(subscription.getId(), renewalInvoice.getId());
        assertThat(subscriptionService.getCurrentSubscription(tenantId).isInDunning()).isFalse();
    }
}
