-- ============================================================
-- V004 — System-generated plan slugs (PLN-0001 format)
-- ============================================================
-- Introduces a dedicated database sequence for Plan slugs.
-- Slugs are no longer caller-supplied; they are generated by
-- the application layer via nextval('ppm_plan_slug_seq').
--
-- This migration:
--   1. Creates the sequence.
--   2. Backfills existing rows (ordered by created_at ASC) so that
--      any pre-existing caller-supplied slugs are replaced with the
--      canonical PLN-XXXX format.
--   3. Advances the sequence past the highest assigned value so that
--      the first nextval() call after migration returns the next
--      unused number.
--
-- The existing uq_ppm_plans_slug partial unique index is unchanged —
-- PLN-XXXX values are still unique strings, and the safety net remains.
-- ============================================================

-- ── Step 1: Create sequence ───────────────────────────────────────────────────
CREATE SEQUENCE ppm_plan_slug_seq
    START WITH 1
    INCREMENT BY 1
    NO CYCLE;

-- ── Step 2: Backfill existing rows ────────────────────────────────────────────
-- Assigns PLN-0001, PLN-0002, ... in created_at ascending order.
-- Rows with equal created_at are ordered by id for determinism.
-- If the table is empty this UPDATE is a no-op.
WITH ordered AS (
    SELECT id,
           ROW_NUMBER() OVER (ORDER BY created_at ASC, id ASC) AS rn
    FROM ppm_plans
)
UPDATE ppm_plans p
SET slug = 'PLN-' || LPAD(o.rn::text, 4, '0')
FROM ordered o
WHERE p.id = o.id;

-- ── Step 3: Advance sequence past highest assigned number ─────────────────────
-- setval(seq, n) sets last_value = n so the next nextval() returns n + 1.
-- If no rows exist max_slug_num is NULL and we skip setval — the sequence
-- will naturally start at 1 (first nextval returns 1 → PLN-0001).
DO $$
DECLARE
    max_slug_num BIGINT;
BEGIN
    SELECT MAX(SUBSTRING(slug FROM 5)::BIGINT)
    INTO   max_slug_num
    FROM   ppm_plans
    WHERE  slug ~ '^PLN-[0-9]+$';

    IF max_slug_num IS NOT NULL THEN
        PERFORM setval('ppm_plan_slug_seq', max_slug_num);
    END IF;
END;
$$;
